// All tags in capitals to make checking easier

export const portfolioData = [
  {
    id: "1",
    imageUrl: "/img/portfolio/no-story-recipes.svg",
    altText: "No Story Recipes",
    title: "No Story Recipes",
    name: "No Story Recipes",
    description:
      "A project where I built a recipe storing application called No Story Recipes using nextjs and nestjs.",
    siteUrl: "https://no-story-recipes.vercel.app",
    siteAria: "View No Story Recipes project website.",
    repoUrl: "https://github.com/andydurette/no-story-recipes-frontend",
    repoAria: "View No Story Recipes project repository.",
    tags: [
      "JAVASCRIPT",
      "NEXT.JS",
      "FULL STACK",
      "MYSQL",
      "PRISMA",
      "TAILWIND",
      "NESTJS",
      "TYPESCRIPT",
    ],
    filter: [
      "JAVASCRIPT",
      "NEXT.JS",
      "FULL STACK",
      "MYSQL",
      "PRISMA",
      "TAILWIND",
      "NESTJS",
      "TYPESCRIPT",
    ],
  },
  {
    id: "2",
    imageUrl: "/img/portfolio/turnnout.svg",
    altText: "Turrnout",
    title: "Turrnout",
    name: "Turrnout",
    description:
      "Built using AWS AppSync Turnnout is a video on demand subscription service offering of dance classes.",
    siteUrl: "https://www.turnnout.com/",
    siteAria:
      "Built using AWS AppSync Turnnout is a video on demand subscription service offering of dance classes.",
    repoUrl: "",
    repoAria: "",
    tags: [
      "HTML5",
      "CSS3",
      "JAVASCRIPT",
      "REACT",
      "NODE",
      "CI/CD",
      "LINT",
      "DEVOPS",
      "FULL STACK",
      "AWS APPSYNC",
      "REDUX TOOLKIT",
      "GRAPHQL",
    ],
    filter: [
      "HTML5",
      "CSS3",
      "JAVASCRIPT",
      "REACT",
      "NODE",
      "CI/CD",
      "LINT",
      "DEVOPS",
      "FULL STACK",
      "AWS APPSYNC",
      "REDUX TOOLKIT",
      "GRAPHQL",
    ],
  },
  {
    id: "3",
    imageUrl: "/img/portfolio/neighbourhood-3.svg",
    altText: "Toronto Neighbourhood Safety app",
    title: "Is My Neighbourhood Safe?",
    name: "Is My Neighbourhood Safe?",
    description:
      "Application that compares crime data by neighbourhood for all of Toronto from 2014 forward, built with HTML, CSS & JS.",
    siteUrl: "https://tns.andydurette.com/",
    siteAria: "View Toronto Neighbourhood safety portfolio website",
    repoUrl: "https://github.com/andydurette/Toronto-Neighborhood-Safety",
    repoAria: "View Toronto Neighbourhood safety github repository",
    tags: [
      "HTML5",
      "CSS3",
      "JAVASCRIPT",
      "NODE",
      "EXPRESS",
      "SASS",
      "FULL STACK",
    ],
    filter: [
      "HTML5",
      "CSS3",
      "JAVASCRIPT",
      "NODE",
      "EXPRESS",
      "SASS",
      "FULL STACK",
    ],
  },
  {
    id: "6",
    imageUrl: "/img/portfolio/nextfantasy.svg",
    altText: "Next Fantasy",
    title: "Next Fantasy",
    name: "Next Fantasy",
    description:
      "Tabletop fantasy site built utilizing next.js dynamic routing, as well as devops practices such as CI/CD pipeline.",
    siteUrl: "https://nextfantasy.vercel.app/",
    siteAria: "Next Fantasy live website",
    repoUrl: "https://github.com/andydurette/nextfantasy",
    repoAria: "Next Fantasy github portfolio",
    tags: [
      "HTML5",
      "CSS3",
      "JAVASCRIPT",
      "NEXTJS",
      "JEST",
      "SASS",
      "CI/CD",
      "LINT",
      "DEVOPS",
      "FRONT END",
    ],
    filter: [
      "HTML5",
      "CSS3",
      "JAVASCRIPT",
      "REACT",
      "NODE",
      "NEXTJS",
      "JEST",
      "SASS",
      "CI/CD",
      "LINT",
      "DEVOPS",
      "FULL STACK",
      "FIREBASE",
    ],
  },
  {
    id: "7",
    imageUrl: "/img/portfolio/30-days.svg",
    altText: "30 day icon challenge",
    title: "Password Generator app",
    name: "30 day icon challenge",
    description:
      "A project where I designed an icon a day for a month in order to better produce vector graphics quickly and efficently.",
    siteUrl: "https://icon-gallery.netlify.app/",
    siteAria: "View 30 Day Icon Challenge portfolio website",
    repoUrl: "https://github.com/andydurette/icon-gallery",
    repoAria: "View 30 Day Icon Challenge portfolio repo",
    tags: [
      "HTML5",
      "CSS3",
      "JAVASCRIPT",
      "REACT",
      "ILLUSTRATOR",
      "UI/UX",
      "FRONT END",
    ],
    filter: [
      "HTML5",
      "CSS3",
      "JAVASCRIPT",
      "REACT",
      "ILLUSTRATOR",
      "UI/UX",
      "FRONT END",
    ],
  },
  {
    id: "8",
    imageUrl: "/img/portfolio/bee.svg",
    altText: "Bees of America",
    title: "Bees of America",
    name: "Bees of America",
    description:
      "A project where I researched the history of bees and utilized React.js, github and Netlify to host a react routed app.",
    siteUrl: "https://bees-react.netlify.app/",
    siteAria: "View Bees of America portfolio website",
    repoUrl: "https://github.com/andydurette/Bees",
    repoAria: "View Bees of America portfolio website",
    tags: [
      "HTML5",
      "CSS3",
      "JAVASCRIPT",
      "REACT",
      "ILLUSTRATOR",
      "SASS",
      "FRONT END",
    ],
    filter: [
      "HTML5",
      "CSS3",
      "JAVASCRIPT",
      "REACT",
      "ILLUSTRATOR",
      "SASS",
      "FRONT END",
    ],
  },
];
